import 'package:drift/drift.dart';

import 'categories_table.dart';
import '../../enums/enums_database.dart';

/// Software table for installable applications.
/// Tabla de software para aplicaciones instalables.
///
/// Maps to PostgreSQL: software
/// Mapea a PostgreSQL: software
@TableIndex(name: 'idx_software_category_id', columns: {#categoryId})
@TableIndex(name: 'idx_software_name', columns: {#name})
@TableIndex(name: 'idx_software_is_active', columns: {#isActive})
@TableIndex(
  name: 'idx_software_category_active',
  columns: {#categoryId, #isActive},
)
class SoftwareTable extends Table {
  /// Table name as generated by Drift for this table. Use for raw queries until
  /// [DatabaseInfra] codegen includes [SoftwareTable] (run build_runner).
  /// Nombre de tabla generado por Drift. Usar en consultas raw hasta que el
  /// codegen de [DatabaseInfra] incluya [SoftwareTable] (ejecutar build_runner).
  static const String driftTableName = 'software_table';

  /// Primary key.
  IntColumn get id => integer().autoIncrement()();

  /// Software name.
  TextColumn get name => text().withLength(max: 255)();

  /// Unique slug for URLs/identifiers.
  TextColumn get slug => text().withLength(max: 255).unique()();

  /// Version string.
  TextColumn get version => text().withLength(max: 50).nullable()();

  /// Foreign key to categories.
  IntColumn get categoryId => integer().references(CategoriesTable, #id)();

  /// Size in MB (nullable, >= 0).
  IntColumn get sizeMb => integer().nullable()();

  /// Description text.
  TextColumn get description => text().nullable()();

  /// Logo path or URL.
  TextColumn get logo => text().withLength(max: 255).nullable()();

  /// Installation type: auto or assisted.
  TextColumn get installationType => textEnum<InstallationTypeEnumDatabase>()
      .withDefault(const Constant('auto'))();

  /// Installer source type.
  TextColumn get installerSourceType =>
      textEnum<InstallerSourceTypeEnumDatabase>().withDefault(
        const Constant('file'),
      )();

  /// Installer source (path, URL, command, etc.).
  TextColumn get installerSource => text().withLength(max: 1000)();

  /// Silent installation arguments.
  TextColumn get silentArgs => text().withLength(max: 1000).nullable()();

  /// Minimum RAM in GB.
  IntColumn get minRamGb => integer().nullable()();

  /// Minimum disk space in GB.
  IntColumn get minDiskGb => integer().nullable()();

  /// Operating system requirement.
  TextColumn get operatingSystem =>
      text().withLength(max: 100).withDefault(const Constant('Windows 10+'))();

  /// Whether installation requires restart.
  BoolColumn get requiresRestart =>
      boolean().withDefault(const Constant(false))();

  /// Whether installation requires internet.
  BoolColumn get requiresInternet =>
      boolean().withDefault(const Constant(false))();

  /// Whether to install dependencies.
  BoolColumn get installDependencies =>
      boolean().withDefault(const Constant(false))();

  /// Whether to run installation in background.
  BoolColumn get backgroundInstall =>
      boolean().withDefault(const Constant(false))();

  /// Whether the software entry is active.
  BoolColumn get isActive => boolean().withDefault(const Constant(true))();

  /// Creation timestamp.
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();

  /// Last update timestamp.
  DateTimeColumn get updatedAt => dateTime().withDefault(currentDateAndTime)();

  @override
  List<Set<Column>> get uniqueKeys => [
    {name, version, installerSource},
  ];
}
